name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ''
          - os: macos-latest
            target: aarch64-apple-darwin
            ext: ''
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: '.exe'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Test
        run: cargo test
      - name: Package binary
        shell: bash
        run: |
          bin_name=kbd_layout_overlay
          out_name=kbd-overlay-${{ matrix.target }}
          bin_path=target/${{ matrix.target }}/release/${bin_name}${{ matrix.ext }}
          mkdir dist
          cp "$bin_path" dist/
          mv dist/${bin_name}${{ matrix.ext }} dist/${out_name}${{ matrix.ext }}
          cd dist
          if [ "$RUNNER_OS" = "Windows" ]; then
            powershell.exe -Command "Compress-Archive -Path ${out_name}${{ matrix.ext }} -DestinationPath ..\\${out_name}.zip"
          else
            zip ../${out_name}.zip ${out_name}${{ matrix.ext }}
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: kbd-overlay-${{ matrix.target }}
          path: kbd-overlay-${{ matrix.target }}.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
